### ISSUE TITLE
What is the most recent version of the CPSV?

### ISSUE THREAD

**Issue by JosePRevenga** [SEMICeu/CPSV#3]
We observed that the CPSV GitHub code repository latest update is 17 month old, but the Joinup downlodable release is 8 month old. During the webinars, we understood that you are currently working on a very recent evolution of CPSV, but that would not be neither the GitHub one nor the Joinup's. 

So, where can we follow-up your progress? 

Thank you in advance.

**Comment by EmidioStani** [comment]
The latest release of CSPV is 1.0.1, uploaded here on GitHub
