### ISSUE TITLE
CCCEV in CPSV and Channel class

### ISSUE THREAD

**Issue by giorgialodi** [SEMICeu/CPSV#4]
The RDF version of the vocabulary there is CCCEV. Is that possible to include the RDF version of CPSV? 

It seems to me that the class Channel is not available/defined, also in other RDF files I have seen in Joinup. Can you confirm that it is not defined? If so, why?

**Comment by EmidioStani** [comment]
The old releases of CPSV have been uploaded.

Indeed the Channel class resides under Core Vocabularies namespace
